package p000;

public class nr implements nc {
    public static final nr aa = new nr(3, 9);
    public static final nr ab = new nr(13, 8);
    public static final nr ac = new nr(23, 11);
    public static final nr ad = new nr(1, 3);
    public static final nr ae = new nr(9, 10);
    public static final nr af = new nr(0, 7);
    public static final nr ag = new nr(4, 4);
    public static final nr ah = new nr(17, 7);
    public static final nr ai = new nr(15, 3);
    public static final nr aj = new nr(8, 5);
    public static final nr ak = new nr(18, 8);
    public static final nr al = new nr(24, 3);
    public static final nr am = new nr(11, 3);
    public static final nr an = new nr(2, 3);
    public static final nr ao = new nr(19, 8);
    public static final nr ap = new nr(25, 0);
    public static final nr aq = new nr(10, -1);
    public static final nr ar = new nr(7, 4);
    public static final nr as = new nr(6, 3);
    public static final nr at = new nr(12, 8);
    public static final nr au = new nr(21, 7);
    public static final nr av = new nr(22, 3);
    public static final nr aw = new nr(14, 8);
    public static final nr ax = new nr(20, 8);
    public static final nr ay = new nr(5, -1);
    public static final nr az = new nr(16, 8);
    public static final nr ba = new nr(42, 2);
    public static final nr bb = new nr(27, 7);
    public static final nr bc = new nr(28, -1);
    public static final nr bd = new nr(44, 15);
    public static final nr be = new nr(38, 0);
    public static final nr bf = new nr(32, 7);
    public static final nr bg = new nr(30, 7);
    public static final nr bh = new nr(31, 3);
    public static final nr bi = new nr(49, -1);
    public static final nr bj = new nr(48, 0);
    public static final nr bk = new nr(39, -2);
    public static final nr bl = new nr(43, -1);
    public static final nr bm = new nr(46, 14);
    public static final nr bn = new nr(41, 0);
    public static final nr bo = new nr(51, 8);
    public static final nr bp = new nr(34, 3);
    public static final nr bq = new nr(50, -2);
    public static final nr br = new nr(47, -1);
    public static final nr bs = new nr(45, -1);
    public static final nr bt = new nr(36, 8);
    public static final nr bu = new nr(37, 7);
    public static final nr bv = new nr(33, 7);
    public static final nr bw = new nr(26, 6);
    public static final nr bx = new nr(35, 6);
    public static final nr by = new nr(40, 7);
    public static final nr bz = new nr(29, 8);
    public static final nr ca = new nr(77, 3);
    public static final nr cb = new nr(68, 16);
    public static final nr cc = new nr(54, 3);
    public static final nr cd = new nr(61, 3);
    public static final nr ce = new nr(72, 8);
    public static final nr cf = new nr(69, 16);
    public static final nr cg = new nr(73, 4);
    public static final nr ch = new nr(62, 8);
    public static final nr ci = new nr(53, 8);
    public static final nr cj = new nr(65, 11);
    public static final nr ck = new nr(58, -1);
    public static final nr cl = new nr(59, 8);
    public static final nr cm = new nr(63, 8);
    public static final nr cn = new nr(57, 2);
    public static final nr co = new nr(55, -2);
    public static final nr cp = new nr(66, 4);
    public static final nr cq = new nr(64, 13);
    public static final nr cr = new nr(71, 8);
    public static final nr cs = new nr(60, 8);
    public static final nr ct = new nr(67, 8);
    public static final nr cu = new nr(76, 9);
    public static final nr cv = new nr(52, 8);
    public static final nr cw = new nr(74, 7);
    public static final nr cx = new nr(75, 3);
    public static final nr cy = new nr(56, -1);
    public static final nr cz = new nr(70, 4);
    public static final nr da = new nr(88, 1);
    public static final nr dc = new nr(79, -1);
    public static final nr dd = new nr(85, -1);
    public static final nr de = new nr(90, -1);
    public static final nr dh = new nr(94, 2);
    public static final nr di = new nr(87, 0);
    public static final nr dj = new nr(78, -1);
    public static final nr dk = new nr(80, 8);
    public static final nr dl = new nr(86, 9);
    public static final nr dm = new nr(97, -1);
    public static final nr dn = new nr(96, 13);
    public static final nr f7do = new nr(81, 3);
    public static final nr dr = new nr(89, 13);
    public static final nr ds = new nr(92, -1);
    public static final nr dt = new nr(82, 9);
    public static final nr dv = new nr(84, 15);
    public static final nr dw = new nr(91, 16);
    public static final nr dx = new nr(93, -1);
    public static final nr dy = new nr(95, -1);
    public static final nr dz = new nr(83, 2);
    final int db;
    final int du;

    nr(int i, int i2) {
        try {
            this.db = 695302905 * i;
            this.du = -827987301 * i2;
        } catch (Throwable e) {
            throw ba.ad(e, "nr.<init>(" + ')');
        }
    }
}
